# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Thom Joy
tagline:
description:
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Thom Joy
  url:               https://twitter.com/thomjoy
  email:             thomjoy1984@gmail.com

# Custom vars
version:             1.0.0
