# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Thom Joy
tagline:             The personal website of Thom Joy
description:         A Software Engineer in Sydney
baseurl:             /blog/
paginate:            3

# About/contact
author:
  name:              Thom Joy
  url:               https://twitter.com/thomjoy
  email:             thomjoy1984@gmail.com

# Custom vars
version:             1.0.0

github:
  repo:              github.com/thomjoy/thomjoy.github.io
